version: "3"

services:
  
  database_sql:
    image: postgres
    container_name: database_sql
    restart: always
    ports: 
      - 5432:5432
      - 9229:9229
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx 
    volumes: 
      - pgdata:/data/postgres
    network_mode: host

  app: 
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata: 
    driver: local